services:
  web:
    image: kubedevio/rotten-potatoes:v1
    ports:
      - "8080:5000"
    networks:
      - aplicacao
    depends_on:
      - mongodb
    environment:
      MONGODB_DB: "admin"
      MONGODB_HOST: "mongodb"
      MONGODB_PORT: "27017"
      MONGODB_USERNAME: "mongouser"
      MONGODB_PASSOWORD: "mongopwd"

  mongodb:
    image: mongo:7.0
    volumes:
      - db_mongo:/data/db
    networks:
      - aplicacao
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd

volumes:
  db_mongo:
  
networks:
  aplicacao:
    driver: bridge